version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/WileyBudgetManagement/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    reviewers:
      - "Bigessfour"
